### PR TITLE
adding support for ec2KeyName

### PR DESCRIPTION
**Pull request by alvinhenrick**
@pishen Adding support for optional attribute ec2KeyName

### CODE REVIEW

**Comment by alvinhenrick** [comment]
@pishen Could you please have a look and see if it's possible to merge ?

**Comment by pishen** [comment]
Could this be done by
```
sparkJobFlowInstancesConfig := sparkJobFlowInstancesConfig.value.withEc2KeyName("your-keypair")
```
as in README?

**Comment by pishen** [comment]
@alvinhenrick I think we can provide this feature. Before I merge, could you change the setting key from `ec2KeyName` to `sparkEc2KeyName`?

**Comment by alvinhenrick** [comment]
@pishen
Done renamed the variable to `sparkEc2KeyName`
I think the way you have implemented is awesome flexibility to allow user to override the settings but I thought it would be good for plugin to support most of the things out of the box so user have to make minimum changes to confgure and it's a build tool plugin. 

Thanks!
Warm Regards,
Alvin.

**Comment by pishen** [comment]
@alvinhenrick Actually, I am not sure what is the definition of "most of the things" here. Everyone has his/her own requirement when running EMR. And it may not be suitable for us to wrap all the functions from Java API, sometimes just to make the line a little bit shorter?

It's still welcome. But I think there're something with higher priority. For example, we may figure out how to write some tests for this plugin when it's growing, or how to handle the cluster name collision problem.

**Pull request merged**
