### PR TITLE
several new features

### PR DESCRIPTION
**Pull request by kailuowang**
* load cluster configuration from s3
 * add multiple additional application to run on emr cluster
 * set separate security group ids for master and slave

### CODE REVIEW

**Comment by kailuowang** [comment]
just found a bug, I am closing for now. will re-open after I fix the bug.

**Comment by kailuowang** [comment]
bug fixed. ready for review.

**Comment by kailuowang** [comment]
@pishen bug fixed. ready for review.

**Comment by pishen** [comment]
Merged, sorry for the late reply. Being busy recently.

**Comment by kailuowang** [comment]
Thank you very much!

**Pull request merged**
